### ISSUE TITLE
How to get volume levels in Java? (Peaks and RMS)

### ISSUE THREAD

**Issue by sblantipodi** [sjoerdvankreel/xt-audio#11]
Hi, 
Congrats for the awesome work here.

I would like to simply get the volume levels (peaks and RMS) of the sound on the default audio output. 
Example, speakers or headphones.

Is this possible in Java using this lib?

Thanks!

**Comment by sjoerdvankreel** [comment]
Hey, xtaudio does I/O only and does not provide any kind of DSP so you'd have to implement that yourself (or find a lib for it). Thanks for the nice words though :)

**Comment by sblantipodi** [comment]
@sjoerdvankreel thanks for the answer, I really appreciate it,
but can I output audio from the speakers to a loopback device?

I'm able to get those infos (rms and peak volume) from a loopback device, the problem is that not every PC have the loopback interface enabled by default.
my idea is to create a loopback device with XT Audio and then get this info with the javax.sound.

Does it have sense? :)

**Comment by sjoerdvankreel** [comment]
It's entirely possible to capture from the default output device using wasapi, loopback streaming is fully supported by xtaudio. It's just the peak and rms calculations you'd have to do yourself.

**Comment by sblantipodi** [comment]
@sjoerdvankreel 
thanks again for the answer.

is there an example on how to capture from the default output device using loopback?
once I have the stream, getting the RMS and Peaks reading shouldn't be that difficult, I think.

Using javax.audio is pretty simple.
When you have a 
TargetDataLine line;
this is all you need to calculate RMS and Peaks, more or less.

```
            while (((b = line.read(buf, 0, buf.length)) > -1) && RUNNING_AUDIO) {
                for (int i = 0, s = 0; i < b; ) {
                    int sample = 0;
                    sample |= buf[i++] & 0xFF; // (reverse these two lines
                    sample |= buf[i++] << 8;   //  if the format is big endian)
                    // normalize to range of +/-1.0f
                    samples[s++] = sample / 32768f;
                }
                float rms = 0f;
                float peak = 0f;
                for (float sample : samples) {
                    float abs = Math.abs(sample);
                    if (abs > peak) {
                        peak = abs;
                    }
                    rms += sample * sample;
                }
                rms = (float) Math.sqrt(rms / samples.length);
                if (lastPeak > peak) {
                    peak = lastPeak * 0.875f;
                }
                lastPeak = peak;
            }
```

is there a way to get something similar to a javax.sound.sampled.TargetDataLine in XT Audio
to apply "my little algorithm"?

**Comment by sjoerdvankreel** [comment]
Hey again. See below for some code that captures from *every* loopback device. Unfortunately (just came to think of it:) there's currently no "official" way to correlate a loopback device to it's corresponding output device. There is support for distinguishing loopback devices from regular input devices though, using the XtDeviceCaps.LOOPBACK flag. Currently you'd have to retrieve the name of the default output device (say it's XYZ) and then search for an input device named "XYZ (Loopback)".

`
package com.mycompany.mavenproject1;

import com.sun.jna.Pointer;
import java.util.EnumSet;
import xt.audio.*;
import xt.audio.Enums.*;
import xt.audio.Structs.*;

public class NewClass {

    static int onBuffer(XtStream stream, XtBuffer buffer, Object o) throws Exception {
        XtSafeBuffer safe = XtSafeBuffer.get(stream);
        safe.lock(buffer);
        float[] samples = (float[]) safe.getInput();
        for (int i = 0; i < buffer.frames; i++) {
            float left = samples[i * 2];
            float right = samples[i * 2 + 1];
            // YOUR CODE HERE
        }
        safe.unlock(buffer);
        return 0;
    }

    public static void main(String[] args) throws Exception {
        try (XtPlatform platform = XtAudio.init("demo", Pointer.NULL)) {
            XtService service = platform.getService(XtSystem.WASAPI);
            try (XtDeviceList list = service.openDeviceList(EnumSet.of(XtEnumFlags.INPUT))) {
                for (int d = 0; d < list.getCount(); d++) {
                    String id = list.getId(d);
                    EnumSet<XtDeviceCaps> caps = list.getCapabilities(id);
                    if (caps.contains(XtDeviceCaps.LOOPBACK)) {
                        try (XtDevice device = service.openDevice(id)) {
                            XtStreamParams streamParams = new XtStreamParams(true, NewClass::onBuffer, null, null);
                            XtFormat format = new XtFormat(new XtMix(48000, XtSample.FLOAT32), new XtChannels(2, 0, 0, 0));
                            XtBufferSize buffer = device.getBufferSize(format);
                            XtDeviceStreamParams deviceParams = new XtDeviceStreamParams(streamParams, format, buffer.current);
                            try (XtStream stream = device.openStream(deviceParams, null);
                                    XtSafeBuffer safe = XtSafeBuffer.register(stream, true)) {
                                stream.start();
                                Thread.sleep(1000);
                                stream.stop();
                            }
                        }
                    }
                }
            }
        } catch (XtException e) {
            System.out.println(XtAudio.getErrorInfo(e.getError()));
        }
    }
}
`

**Comment by sblantipodi** [comment]
@sjoerdvankreel 
wow man, this lib is wow! it works like a charm.

this is what I want to achieve with your lib,
https://youtu.be/ax9pNscWrT0
in that video I was using javax.sound but your lib is obviously way way way better since I can create a loopback on everything.

please let me ask you the last question.

may I reduce the buffer?
I receive 100 info per second, can I lower it to something like 20?

**Comment by sjoerdvankreel** [comment]
Do you mean the frequency with which the callback is invoked? 100 times a second corresponds to a 10 millisecond buffer size which seems about right as that is WASAPI's default buffer size in shared mode. If you want fewer callbacks you actually need to *increase* the buffer size f.e. to 50ms to receive 20 callbacks per second. The line you're looking for is this one:

```
XtDeviceStreamParams deviceParams = new XtDeviceStreamParams(streamParams, format, buffer.current);
```

Anything from buffer.min <= buffer.current <= buffer.max will do. See also here https://sjoerdvankreel.github.io/xt-audio/doc/core/html/struct_xt_buffer_size.html and here https://sjoerdvankreel.github.io/xt-audio/doc/core/html/_xt_device_8h.html#ae1e25aabd778b6a3e3572188072bcd4f.

**Comment by sblantipodi** [comment]
@sjoerdvankreel ok, just integrated your lib into my apps. I'll write it into the credit. release will happen soon.
my app is GPL so it it compatible with your LGPL. 

I'm in love with the work you made here man, it's really very well done, thanks for it,
you added a great perks to the Java world.

I think that you should add a donate button for people like me that appreciate your work.
Hope to seemy app is GPL so it it compatible with your LGPL. 

Thanks!
