### ISSUE TITLE
is it possible to port the code on javascript or something similar?

### ISSUE THREAD

**Issue by GDjkhp** [sjoerdvankreel/xt-audio#14]
processing js has it's own audio thing, but i think it doesn't support real-time like xt-audio, so is it possible to run it on browsers with crossplatform support (android/ios/consoles)? sorry if this was dumb, i know it requires to run on bare metal because it's native code and stuff and requires a lot of processing but damn, i'd asked it anyway…

**Comment by sjoerdvankreel** [comment]
Hey, xt-audio is designed to be low-latency so as you noted it's highly tied to built-in OS functionality, which basically means native code. In theory it might be possible to expose xt-audio via javascript to the browser but that's not something that's on the roadmap (ever). It seems to me (by 5 minute research) that WebAudio is your best best: https://www.html5rocks.com/en/tutorials/webaudio/intro/.

**Comment by GDjkhp** [comment]
ok, how? does webaudio api supports capturing audio from the device loopback?

**Comment by sjoerdvankreel** [comment]
I honestly don't know, I never heard of webaudio untill 2 days ago.
