### ISSUE TITLE
[Not a bug, help needed if possible] Stereo recording

### ISSUE THREAD

**Issue by sblantipodi** [sjoerdvankreel/xt-audio#19]
Hi,
this is not a bug but a simple question, if possible.

Is there a way to distinguish between left and right audio channel in the onBuffer() method?

```
    // Normally don't do I/O in the callback.
    static int onBuffer(XtStream stream, XtBuffer buffer, Object user) throws Exception {
        var output = (FileOutputStream)user;
        XtSafeBuffer safe = XtSafeBuffer.get(stream);
        safe.lock(buffer);
        var input = (byte[])safe.getInput();
        int size = XtAudio.getSampleAttributes(MIX.sample).size;
        output.write(input, 0, buffer.frames * size);
        safe.unlock(buffer);
        return 0;
    }
```

I'm interested in the peak of the recorded track since I would like to use it to create a VU Meter.

I have a working VU Meter based on your lib in a "bigger project called Luciferin" but for now it doesn't separate the left channel from the right one.

https://youtu.be/ax9pNscWrT0

**Comment by sjoerdvankreel** [comment]
What format is this? 24-bit stereo? Then left is in input[0], input[1], input[2], right in [3][4][5], left in [6][7][8], right in [9][10][11] etc. 
Also your call to "output.write(input, 0, buffer.frames * size);" looks suspicious, you should multiply frames*size by the channel count  (i.e. 2 for stereo).

**Comment by sjoerdvankreel** [comment]
Love those peak meters btw :)

**Comment by sblantipodi** [comment]
thank you so much, got it!
I'm creating a new vu meter with separate channels for left and right :D
