### ISSUE TITLE
any plans on supporting 3ms latency for WASAPI shared mode?

### ISSUE THREAD

**Issue by jjYBdx4IL** [sjoerdvankreel/xt-audio#2]
See

http://stackoverflow.com/questions/37468283/how-to-get-below-10ms-latency-using-wasapi-shared-mode

**Comment by sjoerdvankreel** [comment]
It's already supported. See this commit:
https://github.com/sjoerdvankreel/xt-audio/commit/20e082f63c885edbac7a20be83a1fbe6bb950d6d
.
I take it it's not working for you ?

2017-04-30 1:04 GMT+02:00 jjYBdx4IL <notifications@github.com>:

**Comment by jjYBdx4IL** [comment]
Cool stuff. I only tried the example GUI yet and I suppose you can't do mic monitoring with it, correct? Also wasn't able to see see a latency lower than 10ms for WASAPI there, but in that case I'm not sure if my current soundcard has actually support for lower WASAPI buffer sizes. Does the example GUI have any way to see/detect that?

**Comment by sjoerdvankreel** [comment]
You probably need the updated audio drivers. If you're running something fairly standard like realtek hda or the like you can try the drivers i mentioned on the linked stackoverflow question. Wat do you mean by mic monitoring? If you want to simultaneously record mic and playback the recorded signal that's entirely possible, just use an aggregate audio stream on wasapi. Although exclusive mode is probably best, latency wise. This library isn't part of anything bigger, why do you ask ?

**Comment by jjYBdx4IL** [comment]
okay I tested it a bit more. The inbox HDA drivers work in principle, but I cannot reconfigure audio ports with them, so my headphones wouldn't work any more. So, yeah, to get those additional 7ms reduced latency, I'd probably have to get some better audio hardware. Any suggestions?

**Comment by sjoerdvankreel** [comment]
Well indeed i always missed decent low latency audio support on managed environments, both net and java. Thats the main reason i started the project in the first place. 
About the inbox hda stuff, i eventually got it to work with probably the same on-board card (realtek hda) at 3ms latency. What os are you on? You'll need a recent version of windows 10 for this to work.

**Comment by sjoerdvankreel** [comment]
Btw I didn't take the time to package a maven version. It'd be nice if you could do it =)

**Comment by jjYBdx4IL** [comment]
Yeah, Win 10 too. Don't think you can prevent it from updating too long :).

**Comment by sjoerdvankreel** [comment]
Just checked again on my development machine, the gui actually reports buffer sizes as low as 2.7 millis for wasapi shared mode. Did you try updating drivers for your inbox audio as explained here: https://docs.microsoft.com/nl-nl/windows-hardware/drivers/audio/low-latency-audio ?

**Comment by jjYBdx4IL** [comment]
yeah it works with inbox drivers,
