### ISSUE TITLE
About Capturing Sound Card Data and Processing with Java

### ISSUE THREAD

**Issue by Janix520** [sjoerdvankreel/xt-audio#22]
Hello, I would like to create a global DSP for Windows. Currently, I can use your library to read the sound of the Windows system, and I also know the algorithm. The problem is that if I use the filtered sound output, the original sound still exists. How can I replace the original sound, or is there a way to directly filter the original sound, Does your library support this?

**Comment by ofsjoerdk** [comment]
Hey!

I'm not exactly sure where you're going with this. All audio inputs/outputs are separated. You are completely free to read from input, do whatever you want with it, then write to output. Original input should not be audible in this case. Can you share some example code to get an idea of what you're trying to accomplish?

**Comment by Janix520** [comment]
I want to create a global equalizer on Windows, such as using Windows Media Player for playback, which can be filtered in real-time by the equalizer

`public class AudioFilterDemo {

	private boolean stopped = false;
	private static SourceDataLine sourceDataLine;

	int onBuffer(XtStream stream, XtBuffer buffer, Object user) {
		XtSafeBuffer safe = XtSafeBuffer.get(stream);
		if (safe == null) {
			return 0;
		}

		safe.lock(buffer);

		short[] outputAudio = (short[]) safe.getInput();

		// Do some filtering
		// Here we do some filtering, but I do mute processing here, and the speaker
		// output should also be muted
		realTimeFilter(outputAudio);

		// Try using Java sound output because WASAPI doesn't know how to fully duplex
		float[] shortToFloat = DspUtil.shortToFloat(outputAudio);
		byte[] floatToByte = DspUtil.floatToByte(shortToFloat);
		sourceDataLine.write(floatToByte, 0, floatToByte.length);

		safe.unlock(buffer);
		return 0;
	}

	/**
	 * 
	 * @param audio
	 */
	private void realTimeFilter(short[] audio) {
		for (int i = 0; i < audio.length; i++) {
			audio[i] *= 0;
		}
	}

	/**
	 * init output by java sound api
	 */
	public static void initSourceDataLine() {
		int channel = 2;
		AudioFormat targetFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 44100, 16, channel, channel * 2,
				44100, false);

		DataLine.Info dinfo = new DataLine.Info(SourceDataLine.class, targetFormat, AudioSystem.NOT_SPECIFIED);

		try {
			sourceDataLine = (SourceDataLine) AudioSystem.getLine(dinfo);
			sourceDataLine.open(targetFormat);
			sourceDataLine.start();
		} catch (LineUnavailableException e) {
			e.printStackTrace();
		}

	}

	/**
	 * 
	 */
	public void init() {

		initSourceDataLine();

		XtPlatform platform = XtAudio.init(null, null);
		XtService service = platform.getService(XtSystem.WASAPI);

		XtDeviceList openDeviceList = service.openDeviceList(EnumSet.of(XtEnumFlags.INPUT));

		for (int i = 0; i < openDeviceList.getCount(); i++) {
			String id = openDeviceList.getId(i);
			String name = openDeviceList.getName(id);
			EnumSet<XtDeviceCaps> caps = openDeviceList.getCapabilities(id);
			System.out.println(name);

			if (caps.contains(XtDeviceCaps.LOOPBACK)) {
				XtDevice device = service.openDevice(id);

				XtMix mix = new XtMix(48000, XtSample.INT16);
				XtChannels channels = new XtChannels(2, 0, 0, 0);
				XtFormat format = new XtFormat(mix, channels);
				XtBufferSize bufferSize = device.getBufferSize(format);
				XtStreamParams streamParams = new XtStreamParams(true, this::onBuffer, null, null);
				XtDeviceStreamParams deviceParams = new XtDeviceStreamParams(streamParams, format, bufferSize.current);
				try (XtStream stream = device.openStream(deviceParams, null);
						var safeBuffer = XtSafeBuffer.register(stream)) {
					stream.start();
					while (!stopped) {
						Thread.onSpinWait();
					}
					stream.stop();
				}
			}
		}
	}

	public static void main(String[] args) {
		new AudioFilterDemo().init();
	}

}
`


 I don't know how to capture and output the filtered sound correctly. I used the Java sound API to output, but the original sound still exists

**Comment by ofsjoerdk** [comment]
Some comments:

* You are filtering the input. What you should be doing is copy input to output, then filter that instead.
* You don't need SourceDataLine. XtAudio can run full-duplex on top of wasapi. See aggregation example here https://sjoerdvankreel.github.io/xt-audio/ and docs here https://sjoerdvankreel.github.io/xt-audio/doc/core/html/index.html#aggregation, here https://sjoerdvankreel.github.io/xt-audio/doc/core/html/_xt_service_8h.html#a0c01c9e99c5ad18509133f6ce3776b5b and here https://sjoerdvankreel.github.io/xt-audio/doc/java/apidocs/xt.audio/xt/audio/XtService.html#aggregateStream(xt.audio.Structs.XtAggregateStreamParams,java.lang.Object).
* Loopback devices allow you to get your hands on another applications audio output, but you cannot cancel their audio! So in any case you will end up with both the original and the filtered output. Best you can do is record for loopback device X, then filter that and send filtered output to device Y.

**Comment by Janix520** [comment]
Okay, thank you. I'll study it

**Comment by sjoerdvankreel** [comment]
I think the most simple way for you is to copy the aggregation sample from here https://sjoerdvankreel.github.io/xt-audio/. Switch the default input to the loopback device of your choice, switch the output device from default output to another output that does not correspond to the loopback device. Then in onBuffer, where it says "System.arrayCopy", apply your filtering to the copy (output).
