### ISSUE TITLE
[Question] ASIO event detection

### ISSUE THREAD

**Issue by AGENTE44** [sjoerdvankreel/xt-audio#27]
new question
I realized that VB-audio ASIO tester detects when ASIO4ALLv2 is changing the buffer size and then restarts the test
I guess that ASIO4ALLv2 is sending some kind of events to VB-audio, but I haven't found the procedure to detect this in xt, I thought callbacks would do (state change event)
is this feature supported by the xt lib?

greetings

**Comment by sjoerdvankreel** [comment]
<< I guess that ASIO4ALLv2 is sending some kind of events to VB-audio
It's not specific to ASIO4ALL. Any asio driver can do this.

<< I thought callbacks would do (state change event)
No, that's just to detect stream started/stopped. 

<< is this feature supported by the xt lib?
No. I could do it, but to do so properly is quite a bit of work. ASIO can report other stuff besides buffer size changes (like f.e. sample rate changes). Other backends also support similar stuff. There's at least JACK and WASAPI to deal with.

**Comment by AGENTE44** [comment]
ok thanks for the clarification
