### ISSUE TITLE
Exit code -1073741819 (0xC0000005) on VoiceMeeter ASIO

### ISSUE THREAD

**Issue by LolHens** [sjoerdvankreel/xt-audio#3]
Hi! I recently found out about xt-audio and I really like it!
Sadly there seems to be a bug with the Voicemeeter Virtual ASIO device.

I am using the java bindings.
I tried to run the RenderSimple example on it and it didn't work.
Instead the java program just stopped returning exit code -1073741819 (0xC0000005)

I have created a gist with the code and output:
[https://gist.github.com/LolHens/e65d2a34225acebabbd48ab8576e4493](https://gist.github.com/LolHens/e65d2a34225acebabbd48ab8576e4493)

Also I have the question if it could be possible to query a device by its name without opening all devices on a system. Or maybe some unique identifier in case there are multiple devices with the same name.

**Comment by sjoerdvankreel** [comment]
Hey, ASIO bug is fixed in 1.0.5. Querying device names or identifiers should be possible on most backends but it's not currently implemented. Please file a new issue if this is important to you. Please let me know if the last bugfix solved your issue! Closing this for now.

**Comment by LolHens** [comment]
Thank you! I tested the new version and it is working perfectly!
