### ISSUE TITLE
Compile windows dll libraries without external dependencies

### ISSUE THREAD

**Issue by Gusi** [sjoerdvankreel/xt-audio#8]
The dll libraries in the 1.8 version are dynamically linked against the VC runtime, so the runtime must be present in the system for the dll to work. It would be better to compile statically against the VC runtime so it doesn't require any external dependency (the statically linked version is only like 100KB more in size).

**Comment by sjoerdvankreel** [comment]
I dropped static linking support on purpose in v1.7. Although nice in theory, when an application uses multiple libraries all those libraries have to be statically linked to the exact same version of msvcrt.dll. The only viable way to do so is when the application compiles all of it's dependencies from source. See also here: https://stackoverflow.com/questions/787216/should-i-link-to-the-visual-studio-c-runtime-statically-or-dynamically. That post also offers a nice alternative solution suggesting the application deploys it's own private copy of msvcrt.dll to prevent the user having to install it, but then again it's to be handled by the application author, not the library authors. I see no way i can distribute a universally-usable-by-everyone, statically linked version of xt-core.dll.

**Comment by sjoerdvankreel** [comment]
Oh wait, i now see i spoke too soon. From that same post: "The only time you'll get multiple copies of the runtime is when you statically link a library into a DLL - each DLL will get a copy, and so will the exe. If they're all static libraries and not DLLs, they'll all link together and all of your libraries will share the same runtime." 

So that means i can provide dynamically linked .dll/.so and statically linked .lib/.a, but not statically linked .dll/.so. So the static linked libs will only be useful if you work in c/c++, and be of no use to the .net/java bindings. Is this what you need ?

**Comment by Gusi** [comment]
It is the first time that I hear that statically linking the runtime can cause problems; I think it is just the opposite, to avoid the DLL hell of having your application using multiple DLL and each one dynamically instancing different versions of the runtime's DLLs.

If statically linking your DLL with the runtime, you get the code of the runtime that your DLL needs compiled as native code along with your own code. It is not anything about then instancing a "hidden" DLL inside your code, and I don't see how it can cause problems and crashes (of course if a DLL reserves memory and it is freed in another DLL using another runtime, it will crash... but this is a design failure).

In a perfect world all the native code of your application would be linking against the exact same runtime version, but it is not the case. In the past I had to manually add the runtime dependencies of the libraries that I needed, and even sometimes I discovered that there was a dependency when a customer had a problem with the app in his/her computer. 

Right now I have a fork of your code just for having the DLL linked statically, I can live with it, but I would prefer to use the npm packages so I don't need to care about pulling and compiling new versions.

**Comment by Gusi** [comment]
Let me show you an example. 

The original SQLite library, if you download the compiled version from the official webpage, it is linked dynamically against the MSVCRT.DLL (so you need it in your system). But, Microsoft offers you a statically compiled version when using the System.Data.Sqlite package from .NET 5. First one is 937KB, second one 1157KB; the difference is of course the embedded functions of the runtime in the second.

Do you think that Microsoft is offering you a DLL inside their official .NET 5 packages that could crash or bring problems to your app? It is just the opposite... they make the DLL autocontained to not depend on external DLL that can be missing in your target system.

**Comment by sjoerdvankreel** [comment]
Just be clear, so are in fact asking for a xt-core.dll that is statically linked against msvcrt, right? It's not about producing a static xt-core.lib? Also, what language bindings are you using?

**Comment by Gusi** [comment]
Yes, xt-core.dll statically linked against msvcrt. I use C#/.NET 5.

**Comment by sjoerdvankreel** [comment]
Well i could publish 2 versions, one with static and one with dynamic linking. I think this statement "each one dynamically instancing different versions of the runtime's DLLs" is incorrect though, i always thought if everything is linked dynamically (against plain msvcrt, not a specific version of it), then all libraries load the exact same version of msvcrt at runtime and there's only one copy of it in the programs address space (correct me if im wrong, but i'd like to see this documented somewhere).

Anyway as of 1.7 xt-core.dll does never return stuff it allocated back the caller to free() directly, so there should be less of a problem. Especially with the c# bindings which manage all that stuff inside the managed dll.

**Comment by Gusi** [comment]
Exactly the problem is that you need to compile all your dlls against the same exact msvcrt version for that to happen, but if you link against different versions, then the hell is there (now imagine using your dll linking against the XX.XX version of the msvcrt, and the sqlite.dll linking against the YY.YY version; that's the real problem)

If you compile two versions it would be perfect for me, I will just choose the statically linked version.
Thanks!

**Comment by sjoerdvankreel** [comment]
Ah yes, you're absolutely right. This stuff always gets to me. That's where the msvc redistributable installer comes in, right? So just to set my head straight: dynamic linking will load 1 copy of msvcrt for each version finally required by the application into the process, and static linking will load 1 copy of msvcrt for each statically-linked library, even if they are linked to the same version, correct ?

I will look into this further probably sometime this week. This not only affects .net packaging but also the java/maven package and the distribution of the native binaries, so might take some time. Have to figure out if i want 1 or 2 .nupkg's, for example.

**Comment by Gusi** [comment]
> Ah yes, you're absolutely right. This stuff always gets to me. That's where the msvc redistributable installer comes in, right?

Yes

> So just to set my head straight: dynamic linking will load 1 copy of msvcrt for each version finally required by the application into the process, and static linking will load 1 copy of msvcrt for each statically-linked library, even if they are linked to the same version, correct ?

Yes and no. It is not a full copy of the msvcrt, it only compiles inside the dll the functions needed from the msvcrt for that specific dll to work (linking statically only takes referenced functions, not all the functions inside the msvcrt)

> I will look into this further probably sometime this week. This not only affects .net packaging but also the java/maven package and the distribution of the native binaries, so might take some time. Have to figure out if i want 1 or 2 .nupkg's, for example.

IMHO you should go only for static linking, because if you go with dynamic, you could get requests from other users to have xt-audio linked against the MSVCRT from VS2015, VS2017 o VS2019 depending on their projects. One thing is sure, no one wants to mix different MSVCRT loaded dynamically in the same process, although it could work.

**Comment by sjoerdvankreel** [comment]
Im gonna read up a bit more about this. I was always under the impression that libraries best link dynamically to the runtime, and applications can pretty much do whatever they want. But i now see the advantage i thought i'd had by dynamic linking (mainly correctness, no runtime errors due to mixing versions etc) are not actually achieved simply by linking dynamically. 

Any thoughts on linux static linking? libc.so is also versioned.

**Comment by sjoerdvankreel** [comment]
Ok, im convinced on static for windows. Not sure for linux though. This here https://stackoverflow.com/questions/21876174/linux-c-c-standard-library-static-vs-dynamic-linking?noredirect=1&lq=1 says "if you want to distribute the software as a Linux binary that runs on "any" system (...) you will end up with the same dll (or .so) hell problem as on windows. You don't know which versions of which libraries are on the system. Thus, you will have to provide your own .so files or link statically.". Then this here https://stackoverflow.com/questions/3430400/linux-static-linking-is-dead says "I do not know where to find the historic references, but yes, static linking is dead on GNU systems..." (thats from 10 years ago though), and then more recent answers go on to say its getter better/more supported again these days, but im not entirely convinced that'll work with standard libc, too.

**Comment by Gusi** [comment]
About linux I can't help because my experience is quite limited and I don't fully understand how the libc works with applications when it is updated. I will try to read about it!

About Windows, I think you are on the right track :)

**Comment by sjoerdvankreel** [comment]
Still you compiled for ARM which i havent managed to do so far :)  Found this https://insanecoding.blogspot.com/2012/07/creating-portable-linux-binaries.html which seams a reasonably way to do static linking on linux. Have yet to decide whether to only offer statically linked versions or make it a runtime switch to XtAudioInit because im still not entirely clear on the linux side of things.

**Comment by sjoerdvankreel** [comment]
Just pushed 1.9.0-beta1 to nuget. Could take a while for it to become visible. Native binary size has about doubled so thats probably a good thing. Would you mind running some tests on a barebones machine/vm without the vc runtime installed? I haven't got one lying around at the moment. But some local tests suggest its working just fine.

**Comment by sjoerdvankreel** [comment]
Static linking libgcc and libstdc++ seems to work well. Im going to refrain from static linking libc since that apparently is some sort of rabbithole, see https://www.systutorials.com/how-to-statically-link-c-and-c-programs-on-linux-with-gcc/. Im kind of at a loss about what to do with the backend specific libs (asound, pulse, jackd) though. Gonna need some time to investigate.

**Comment by sjoerdvankreel** [comment]
https://stackoverflow.com/questions/66017579/static-linking-of-linux-audio-libraries. Fingers crossed.

**Comment by Gusi** [comment]
> Just pushed 1.9.0-beta1 to nuget. Could take a while for it to become visible. Native binary size has about doubled so thats probably a good thing. Would you mind running some tests on a barebones machine/vm without the vc runtime installed? I haven't got one lying around at the moment. But some local tests suggest its working just fine.

I will test. In the meantime, to know exactly what dll are required by a .exe/.dll file, you can use https://dependencywalker.com/. It is the standard tool in windows for the job

**Comment by sjoerdvankreel** [comment]
Old:
![old](https://user-images.githubusercontent.com/2647549/106733826-a21a2900-6612-11eb-90be-13214399adcc.png)

New: 
![new](https://user-images.githubusercontent.com/2647549/106733927-bfe78e00-6612-11eb-80d4-753e27a15e11.png)

I guess thats about as good as it gets seeing as the rest are system libraries.

**Comment by Gusi** [comment]
I will check in the afternoon my build, because I think that mine doesn't have a dependency on avrt, but I'm not sure and can't test it right now. Bu definetively the vcruntime is not there anymore.

**Comment by sjoerdvankreel** [comment]
Avrt is for wasapi support only, so if you build without then it should be gone.

**Comment by sjoerdvankreel** [comment]
Finally found something that explains this in a bit more detail: https://github.com/andrewrk/libsoundio/issues/47. Libsoundio like xtaudio is a uniform interface over multiple audio backends so its functionality and dependencies are quite similar, but it seems a bit more linux-oriented. Key points mentioned are:

(1)  "... in general, on Linux it is recommended to use shared libraries. But building statically should work too, and in fact I believe libsoundio provides a static library as well as a shared library by default ..."  and
(2) "So, to summarize, when targeting an Unix, one must ensure that each selected backend:
    Has its client libraries statically linked into the program
    Or that the client libraries installation are enforced by a package dependency
    Or that the client libraries are shipped along the program".

Based on that i lean towards providing both dlls/sos that are statically and dynamically linked to their dependencies (with the exception of libc for linux) and for net/java make it a runtime switch to select the native library. Now on to the next problem, LDD output makes me not happy at all:

	linux-vdso.so.1 (0x00007ffcc9d14000)
	libjack.so.0 => /lib/x86_64-linux-gnu/libjack.so.0 (0x00007ff7e4c0b000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007ff7e4b14000)
	libpulse-simple.so.0 => /lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007ff7e4b0d000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007ff7e4ab8000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff7e48d7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff7e48bc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff7e46c8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff7e4c9b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff7e46a5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff7e469a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff7e4694000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff7e4545000)
	libpulsecommon-13.99.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so (0x00007ff7e44c1000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ff7e4470000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ff7e4446000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ff7e4399000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007ff7e438d000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007ff7e4310000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007ff7e4108000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007ff7e40f3000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007ff7e40ed000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ff7e40e5000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff7e40be000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ff7e409d000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ff7e3f7d000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007ff7e3f60000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007ff7e3f22000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007ff7e3f15000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007ff7e3ee7000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007ff7e3e3c000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007ff7e3e1e000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ff7e3e04000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ff7e3de1000)

What on earth is libsndfile, ogg/vorbis and flac doing there... I only do raw pcm i/o, no disk i/o, no compresses formats whatsoever. May be worth a try to get my hands on a trimmed down version of pulse (which im guessing is pulling those in).

**Comment by Gusi** [comment]
https://codeyarns.com/tech/2015-12-16-how-to-view-hierarchy-of-shared-library-dependencies-using-lddtree.html

**Comment by sjoerdvankreel** [comment]
Yeah it's pulse. Going to investigate further.

**Comment by sjoerdvankreel** [comment]
There seems to be no real way apart from "build from source" to get this right on linux. Not going to do that as it will greatly complicate the build scripts. Furthermore everything linux-related i read still discourages static linking. And finally there's this: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1089 which basically says "static PulseAudio not tested". Which is a shame, because Pulse here is the "worst offender". A build without PA leaves me with less then half of the dependencies. But anayway, if anything is linked shared, then everything can be linked shared, seeing as all of pulse, jack, and alsa bring in libstdc++.so & friends so i gain nothing by static linking myself while relying on shared libraries for all dependencies. So that settles it, it's static for win32, shared for linux.

**Comment by sjoerdvankreel** [comment]
Fixed in v1.9.
